global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: kong
    static_configs:
      - targets: ["kong:8100"]
  - job_name: nats
    static_configs:
      - targets: ["nats:8222"]
  - job_name: core-go
    metrics_path: /metrics
    static_configs:
      - targets: ["core-go:8080"]
  - job_name: node-exporter
    static_configs:
      - targets: ["netdata:19999"]
