tunnel: 6bf6719c-e9af-411b-a7cf-4ad5059804d3
credentials-file: /etc/cloudflared/credentials.json

ingress:
  - hostname: sunmart.online
    service: http://127.0.0.1:8000
  - service: http_status:404
